// AN EXAMPLE OF POSSIBLE PARAMETERS FOR PACKAGE.JSON
module.exports = {
  name: "",
  version: "",
  description: "",
  keywords: [],
  homepage:"",
  bugs : {},
  license : "" ,
  author : {},
  contributors: {},
  files: [],
  main: "",
  browser: "",
  bin: {},
  man: {},
  directories: [],
  repository: {},
  scripts: {},
  config: {},
  dependencies: {},
  devDependencies: [],
  peerDependencies: [],
  bundledDependencies: [],
  optionalDependencies: [],
  engines: "",
  os : [],
  private: ""
}
